USE classicmodels;

CREATE TABLE carrinho (
    CODIGOCLIENTE INT NOT NULL,
    CODIGOPRODUTO VARCHAR(10),
    QUANTIDADE INT,
    PRECO DECIMAL(10,2),
    PRIMARY KEY (CODIGOCLIENTE, CODIGOPRODUTO)
) ENGINE=INNODB;

DELIMITER $

CREATE PROCEDURE GERAR_ITEM_PEDIDO (IN PARAM_CODIGOPRODUTO VARCHAR(10), IN PARAM_QUANTIDADE INT, IN PARAM_PRECO DECIMAL(10,2), IN PARAM_NUMEROPEDIDO INT, IN PARAM_ORDERLINEBNUMBER INT, OUT ERRO VARCHAR(100))
inicio: BEGIN 
    DECLARE PRODUTO_EXISTENTE INT;
    DECLARE QUANTIDADE_ESTOQUE INT;

    -- Verifica se o produto existe e obter a quantidade em estoque
    SELECT COUNT(*), IFNULL(QUANTITYINSTOCK, 0) INTO PRODUTO_EXISTENTE, QUANTIDADE_ESTOQUE
    FROM PRODUCTS 
    WHERE PRODUCTCODE = PARAM_CODIGOPRODUTO;

    -- Verifica se o produto foi encontrado
    IF PRODUTO_EXISTENTE = 0 THEN
        SET ERRO = 'Produto inválido';
        LEAVE inicio;
    END IF;

    -- Verifica se a quantidade em estoque é suficiente
    IF QUANTIDADE_ESTOQUE < PARAM_QUANTIDADE THEN
        SET ERRO = CONCAT('Quantidade do produto ', PARAM_CODIGOPRODUTO, ' inválida');
        LEAVE inicio;
    END IF;

    -- Inseri o item no pedido
    INSERT INTO ORDERDETAILS 
        VALUES (PARAM_NUMEROPEDIDO, PARAM_CODIGOPRODUTO, PARAM_QUANTIDADE, PARAM_PRECO, PARAM_ORDERLINEBNUMBER);
    
    -- Atualizar quantidade em estoque
    UPDATE PRODUCTS 
    SET QUANTITYINSTOCK = QUANTITYINSTOCK - PARAM_QUANTIDADE 
    WHERE PRODUCTCODE = PARAM_CODIGOPRODUTO;
    
    SET ERRO = '';
END$

CREATE PROCEDURE GERAR_PEDIDO (IN PARAM_CLIENTE INT, IN PARAM_VENDEDOR INT, OUT RESULTADO VARCHAR(200))
inicio: BEGIN
    DECLARE VAR_EXISTECLIENTE INT DEFAULT 0;
    DECLARE VAR_EXISTEVENDEDOR INT DEFAULT 0;
    DECLARE VAR_COMPROUPRODUTO INT DEFAULT 0;
    DECLARE VAR_NUMEROPEDIDO INT DEFAULT 0;
    DECLARE VAR_CODIGOPRODUTO VARCHAR(10);
    DECLARE VAR_QUANTIDADE INT;
    DECLARE VAR_PRECO DECIMAL(10,2);
    DECLARE CONT INT DEFAULT 0;
    DECLARE CONTADOR_WHILE INT DEFAULT 0;
    DECLARE ERRO VARCHAR(100);

    -- Inicia transação
    START TRANSACTION;

    -- Obtem o próximo número do pedido
    SELECT IFNULL(MAX(ORDERNUMBER), 0) + 1 INTO VAR_NUMEROPEDIDO FROM ORDERS;

    -- Verifica a existência do cliente
    SELECT COUNT(*) INTO VAR_EXISTECLIENTE
    FROM CUSTOMERS
    WHERE CUSTOMERNUMBER = PARAM_CLIENTE;

    IF VAR_EXISTECLIENTE = 0 THEN
        SET RESULTADO = 'CLIENTE NÃO ENCONTRADO NA BASE DE DADOS';
        ROLLBACK;
        LEAVE inicio;
    END IF;

    -- Verifica a existência do vendedor
    SELECT COUNT(*) INTO VAR_EXISTEVENDEDOR
    FROM EMPLOYEES
    WHERE EMPLOYEENUMBER = PARAM_VENDEDOR;

    IF VAR_EXISTEVENDEDOR = 0 THEN
        SET RESULTADO = 'VENDEDOR NÃO ENCONTRADO NA BASE DE DADOS';
        ROLLBACK;
        LEAVE inicio;
    END IF;

    -- Verifica se o carrinho está vazio
    SELECT COUNT(*) INTO VAR_COMPROUPRODUTO
    FROM CARRINHO
    WHERE CODIGOCLIENTE = PARAM_CLIENTE;

    IF VAR_COMPROUPRODUTO = 0 THEN
        SET RESULTADO = 'O CARRINHO ESTÁ VAZIO';
        ROLLBACK;
        LEAVE inicio;
    END IF;

    -- Verifica o limite de crédito do cliente
    IF (SELECT CREDITLIMIT FROM CUSTOMERS WHERE CUSTOMERNUMBER = PARAM_CLIENTE) < 0 THEN
        SET RESULTADO = 'O CLIENTE NÃO POSSUI LIMITE DE CRÉDITO';
        ROLLBACK;
        LEAVE inicio;
    END IF;

    -- Inseri o pedido
    INSERT INTO ORDERS (ORDERNUMBER, ORDERDATE, REQUIREDDATE, SHIPPEDDATE, STATUS, COMMENTS, CUSTOMERNUMBER)
    VALUES (VAR_NUMEROPEDIDO, CURDATE(), CURDATE() + INTERVAL 7 DAY, NULL, 'processing', '', PARAM_CLIENTE);

    -- Obtem o número total de itens no carrinho
    SELECT COUNT(*) INTO CONT FROM CARRINHO WHERE CODIGOCLIENTE = PARAM_CLIENTE;

    -- Processa cada item do carrinho
    WHILE CONTADOR_WHILE < CONT DO
        SET ERRO = '';

        -- Obte detalhes do item no carrinho
        SELECT CODIGOPRODUTO, QUANTIDADE, PRECO INTO VAR_CODIGOPRODUTO, VAR_QUANTIDADE, VAR_PRECO
        FROM CARRINHO 
        WHERE CODIGOCLIENTE = PARAM_CLIENTE 
        LIMIT 1 OFFSET CONTADOR_WHILE;
        
        -- Gera item do pedido
        CALL GERAR_ITEM_PEDIDO(VAR_CODIGOPRODUTO, VAR_QUANTIDADE, VAR_PRECO, VAR_NUMEROPEDIDO, CONTADOR_WHILE + 1, ERRO);
        
        -- Verifica se houve erro
        IF ERRO != '' THEN
            ROLLBACK;
            SET RESULTADO = ERRO;
            LEAVE inicio;
        END IF;

        SET CONTADOR_WHILE = CONTADOR_WHILE + 1;
    END WHILE;

    -- Atualiza vendedor
    UPDATE CUSTOMERS SET SALESREP_EMPLOYEENUMBER = PARAM_VENDEDOR WHERE CUSTOMERNUMBER = PARAM_CLIENTE;

    -- Confirma a transação
    COMMIT;

    SET RESULTADO = CONCAT('Pedido gerado: ', VAR_NUMEROPEDIDO);

    -- Limpa o carrinho
    DELETE FROM CARRINHO WHERE CODIGOCLIENTE = PARAM_CLIENTE;

END$
DELIMITER ;

-- Testa o procedimento
INSERT INTO CARRINHO VALUES (103, 'a', 10, 10);
CALL GERAR_PEDIDO(103, 1002, @resultado);

-- Cria tabela para armazenar resultados
CREATE TABLE resultado (
    id VARCHAR(100)
);

-- Inseri e verificar o resultado
INSERT INTO resultado VALUES (@resultado);
SELECT * FROM resultado;
SELECT * FROM CARRINHO;


